nameOverride: ""
fullnameOverride: ""
imagePullSecrets: []
resources: {}
nodeSelector: {}

image:
  repository: ghcr.io/luukvdm/otemplate
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""
