apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "otemplate.fullname" . }}
  labels:
    {{- include "otemplate.labels" . | nindent 4 }}
spec:
  replicas: 1
  {{- with .Values.imagePullSecrets }}
  imagePullSecrets:
    {{- toYaml . | nindent 8 }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "otemplate.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "otemplate.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - name: {{ .Chart.Name }}
        securityContext:
          {{- toYaml .Values.securityContext | nindent 12 }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        resources:
          {{- toYaml .Values.resources | nindent 12 }}
status: {}
